name: github-action
on: [push]
jobs:
    test:
        runs-on: ubuntu-latest
        container: pytorch/pytorch:1.8.1-cuda11.1-cudnn8-runtime
        steps:
            - uses: actions/checkout@v2
            - run: pip install pytest
            - run: py.test
